### PR TITLE
Define `kahypar_set_seed`, `kahypar_validate_input`, `kahypar_read_hypergraph_from_file`

### PR DESCRIPTION
**Pull request by mofeing**
Adds some functions from the C API that are not yet in the Julia API.

### CODE REVIEW

**Comment by SebastianSchlag** [comment]
Thanks for adding those functions. 👍 

LGTM, but will let @jalving, since he developed the interface.

**Comment by mofeing** [comment]
I also would like to add the `kahypar_supress_output` function added in kahypar/kahypar#190 but that required another release right?

**Comment by jalving** [comment]
Hey @mofeing; thanks for adding these! 

Yes, we will need to create a new kahypar binary for Julia. I will work on that soon.  In the meantime, I have been using the Julia Suppressor package to suppress output from KaHyPar.jl.

**Comment by mofeing** [comment]
Thanks, I will try Suppressor meanwhile.

**Pull request merged**
